sudo: required
dist: xenial
services:
- docker
language: python
python:
- '2.7'
- '3.6'
- '3.7'
install:
- pip install flake8
script:
- flake8 .
before_deploy:
- python setup.py bdist_wheel
deploy:
  provider: pypi
  user: adalekin
  password:
    secure: Ae1yNgwnKtSO7d0EfNDT8vzmpFDVSfNcCuQ+6gC1F/IJcQuxl1WnXmFW58BNUFJiypCdU9/0nGK1z8VLyyANbP57XQDxC/lLrO4XgX5onC4tZptVFX3e4xsPKYuhdoIZZkWmHDhxt7adNpyexguig5sXUGY4IRtFrC1K6+dJR0edAyFGGS64EzISr2wj1W6gvQ8tT7AlcnISHr1eH+HARLiIPebDCTQz/su8N4ofAAgCU20RPN/XArcJa4ObuYNAo8n2Yb2nlgpog4ZqfIiYJsP3shVF9ubNSDUdw+XcccLysYhzM+0Xq1192Dr3cDdjopAtUxl8E2bk1rWtG/CrVeWeF4KT9R1zufDRdPNGLcB94suC2uHVLlTBa/2Oz2R72A7pQnQ9DDsRcEsZ7SDifzv+1sTEVb4EsCVJIWtcvDMN4ABd89Ro+TxAgrh2kadBiiE7ZVZZCAtTy8ATVMkDnB37KsWEXhB1Rlkz5WG5H8Q11DjiQAHn4lXMJRpbyBSP54q8bWospGvwK6BceFx3+0WQfAXn4uoZ9cXSNzwGEZ0fzH/AQLfsqvgNvS8Cse13YG8imnbiw4TCMgriIHi5SzOjNNRWMaLcFE1XkDRw9r11eq4Jh4KcX5SnNw7e9hpJuZ1jxG4g31/pG+90POh2lJYzw3ogAUN7n0UhH763EOk=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
